[package]
name = "ruroco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.64"
clap = { version = "4.5.4", features = ["derive", "string"] }
regex = "1.10.4"
log = "0.4.21"
env_logger = "0.11.3"
