[package]
name = "ruroco"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.64" }
clap = { version = "4.5.4", features = ["derive", "string"] }
log = "0.4.21"
env_logger = "0.11.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.13"

[dev-dependencies]
rand = "0.8.5"

[profile.release]
opt-level = "z"       # Optimize for binary size
strip = true          # Automatically strip symbols from the binary
debug = true          # debug information
lto = true            # Enable Link Time Optimization
codegen-units = 1     # Optimize for single codegen unit (better performance)
panic = 'abort'       # Abort on panic (smaller binary size)

